export const global_states = {
  wallet: '',
  generatorModal: 'scale-0',
  winnerModal: 'scale-0',
  authModal: 'scale-0',
  chatModal: 'scale-0',
  jackpots: [],
  jackpot: null,
  result: null,
  group: null,
  currentUser: null,
  luckyNumbers: [],
  participants: [],
  purchasedNumbers: [],
}
